# PersuContraGraph 训练配置 - 第一阶段(align)

# 数据配置
data:
  # 指定大模型列表 (n个模型)
  models:
    - "gpt-5-mini-2025-08-07"
    - "deepseek-v4-flash"
    - "qwen3.6-flash"
    - "grok-4-1-fast-reasoning"

  # 各划分对应的数据集名称
  train_datasets:
    - "CoAID"
    - "ECTF"
  val_datasets:
    - "CoAID"
    - "ECTF"
  test_datasets:
    - "CoAID"
    - "ECTF"
    - "EUDisinfo"
    - "ISOTFakeNews"
    - "MultiDis"

  data_dirs:
    - "data/pcot_persu_data"
    - "data/role_data"
    - "data/emo_data"

  max_length: 512
  batch_size: 128

  # 标签平滑超参数 alpha
  alpha: 0.18958373223309105

# 模型配置
model:
  encoder_name: "../weights/roberta-large"
  pooling: "gated"
  freeze_encoder: true
  persu_hidden: 32
  cls_hidden: 256
  num_classes: 2
  dropout: 0.32901791493317983
  num_learnable_queries: 3
  num_hetero_attention: 1

# 训练配置
train:
  stage: "align"
  epochs: 10
  learning_rate: 0.0006536264082965735
  weight_decay: 0.0006903717055434685
  patience: 7
  device: "cuda:4"
  pretrained_path: ""
  seed: 42

# 保存配置
save:
  save_path: "weights/extax_stage1_opt0_14.pth"